export interface Formula {
  id: string;
  name: string;
  category: string;
  equation: string;
  description: string;
  example?: string;
}

export interface Exercise {
  id: string;
  question: string;
  category: string;
  parameters: {
    [key: string]: number;
  };
  correctValue: number;
  unit: string;
  explanation: string;
}

export const FORMULA_CATEGORIES = [
  'Bảng Cân Đối Kế Toán',
  'Báo Cáo Kết Quả Kinh Doanh',
  'Quản Lý Hàng Tồn Kho',
  'Tính Giá Thành',
  'Phân Tích Tài Chính',
  'Thuế & Khấu Hao',
  'Kế Toán Quản Trị',
  'Ngân Sách & Dòng Tiền'
];

export const formulas: Formula[] = [
  { id: 'f1', name: 'Phương trình kế toán cơ bản', category: 'Bảng Cân Đối Kế Toán', equation: 'Tài sản = Nợ phải trả + Vốn chủ sở hữu', description: 'Nền tảng của bảng cân đối kế toán.', example: 'Nợ: 100, Vốn CSH: 200 => Tài sản: 300.' },
  { id: 'f2', name: 'Doanh thu thuần', category: 'Báo Cáo Kết Quả Kinh Doanh', equation: 'Doanh thu thuần = Doanh thu bán hàng - Các khoản giảm trừ', description: 'Doanh thu thực tế sau khi trừ chiết khấu, giảm giá.', example: 'Doanh thu: 1000, Chiết khấu: 50 => DT thuần: 950.' },
  { id: 'f3', name: 'Lợi nhuận gộp', category: 'Báo Cáo Kết Quả Kinh Doanh', equation: 'Lợi nhuận gộp = Doanh thu thuần - Giá vốn hàng bán', description: 'Phản ánh hiệu quả sản xuất kinh doanh trực tiếp.' },
  { id: 'f4', name: 'Giá trị hàng tồn kho (FIFO)', category: 'Quản Lý Hàng Tồn Kho', equation: 'Hàng tồn cuối = Số lượng tồn * Đơn giá nhập gần nhất', description: 'Nhập trước - Xuất trước.' },
  { id: 'f5', name: 'Khấu hao đường thẳng', category: 'Thuế & Khấu Hao', equation: 'Khấu hao năm = (Nguyên giá - Giá trị thanh lý) / Thời gian sử dụng', description: 'Phân bổ đều nguyên giá TSCĐ.' },
  { id: 'f6', name: 'Tỷ suất lợi nhuận trên doanh thu (ROS)', category: 'Phân Tích Tài Chính', equation: 'ROS = (Lợi nhuận sau thuế / Doanh thu thuần) * 100%', description: 'Hiệu quả sinh lời trên doanh thu.' },
  { id: 'f7', name: 'Vốn lưu động ròng', category: 'Phân Tích Tài Chính', equation: 'Vốn lưu động = Tài sản ngắn hạn - Nợ ngắn hạn', description: 'Khả năng thanh khoản của doanh nghiệp.' },
  { id: 'f8', name: 'Tỷ số thanh toán hiện hành', category: 'Phân Tích Tài Chính', equation: 'Thanh toán hiện hành = Tài sản ngắn hạn / Nợ ngắn hạn', description: 'Đo lường khả năng trả nợ ngắn hạn.' },
  { id: 'f9', name: 'Vòng quay hàng tồn kho', category: 'Quản Lý Hàng Tồn Kho', equation: 'Vòng quay HTK = Giá vốn hàng bán / Hàng tồn kho bình quân', description: 'Số lần luân chuyển kho trong kỳ.' },
  { id: 'f10', name: 'Điểm hòa vốn (Sản lượng)', category: 'Tính Giá Thành', equation: 'Sản lượng hòa vốn = Tổng định phí / (Giá bán - Biến phí đơn vị)', description: 'Mức sản lượng không lãi không lỗ.' },
  { id: 'f11', name: 'Tỷ suất lợi nhuận trên vốn chủ sở hữu (ROE)', category: 'Phân Tích Tài Chính', equation: 'ROE = (Lợi nhuận sau thuế / Vốn chủ sở hữu bình quân) * 100%', description: 'Hiệu quả sử dụng vốn cổ đông.' },
  { id: 'f12', name: 'Giá bình quân gia quyền', category: 'Quản Lý Hàng Tồn Kho', equation: 'Đơn giá bình quân = Tổng giá trị nhập / Tổng số lượng nhập', description: 'Tính giá trị hàng xuất kho bình quân.' },
  { id: 'f13', name: 'Tỷ suất thanh toán nhanh', category: 'Phân Tích Tài Chính', equation: 'Thanh toán nhanh = (Tài sản ngắn hạn - Hàng tồn kho) / Nợ ngắn hạn', description: 'Đánh giá khả năng thanh toán ngay lập tức.' },
  { id: 'f14', name: 'Tỷ suất lợi nhuận trên tổng tài sản (ROA)', category: 'Phân Tích Tài Chính', equation: 'ROA = (Lợi nhuận sau thuế / Tổng tài sản bình quân) * 100%', description: 'Hiệu quả sử dụng tài sản.' },
  { id: 'f15', name: 'Hệ số Nợ (D/A)', category: 'Phân Tích Tài Chính', equation: 'Hệ số nợ = Tổng nợ phải trả / Tổng tài sản', description: 'Phần trăm tài sản được tài trợ bởi nợ.' },
  { id: 'f16', name: 'Vòng quay các khoản phải thu', category: 'Phân Tích Tài Chính', equation: 'Vòng quay phải thu = Doanh thu thuần / Phải thu khách hàng bình quân', description: 'Tốc độ thu hồi nợ khách hàng.' },
  { id: 'f17', name: 'Kỳ thu tiền bình quân', category: 'Phân Tích Tài Chính', equation: 'Kỳ thu tiền = 360 / Vòng quay các khoản phải thu', description: 'Số ngày trung bình để thu hồi công nợ.' },
  { id: 'f18', name: 'Vòng quay vốn lưu động', category: 'Phân Tích Tài Chính', equation: 'Vòng quay vốn lưu động = Doanh thu thuần / Vốn lưu động bình quân', description: 'Hiệu quả sử dụng vốn ngắn hạn.' },
  { id: 'f19', name: 'Số dư đảm phí', category: 'Kế Toán Quản Trị', equation: 'Số dư đảm phí = Doanh thu - Biến phí', description: 'Phần doanh thu còn lại sau khi bù đắp biến phí.' },
  { id: 'f20', name: 'Tỷ lệ số dư đảm phí', category: 'Kế Toán Quản Trị', equation: 'Tỷ lệ SDĐP = (Số dư đảm phí / Doanh thu) * 100%', description: 'Tỷ lệ đóng góp của doanh thu vào lợi nhuận.' },
  { id: 'f21', name: 'Biên độ an toàn (Sản lượng)', category: 'Kế Toán Quản Trị', equation: 'Biên độ an toàn = Sản lượng hiện tại - Sản lượng hòa vốn', description: 'Mức giảm sản lượng cho phép trước khi lỗ.' },
  { id: 'f22', name: 'Đòn bẩy hoạt động (DOL)', category: 'Kế Toán Quản Trị', equation: 'DOL = Số dư đảm phí / Lợi nhuận thuần', description: 'Mức độ biến động của lợi nhuận khi doanh thu thay đổi.' },
  { id: 'f23', name: 'Giá thành sản phẩm xây lắp', category: 'Tính Giá Thành', equation: 'Giá thành = Chi phí NVLTT + Chi phí NCTT + Chi phí SXC', description: 'Tổng hợp chi phí sản xuất trực tiếp.' },
  { id: 'f24', name: 'Hệ số thanh toán tức thời', category: 'Phân Tích Tài Chính', equation: 'Thanh toán tức thời = Tiền và tương đương tiền / Nợ ngắn hạn', description: 'Khả năng trả nợ bằng tiền mặt.' },
  { id: 'f25', name: 'Vốn chủ sở hữu cuối kỳ', category: 'Bảng Cân Đối Kế Toán', equation: 'Vốn CSH cuối = Vốn CSH đầu + Lợi nhuận thuần - Cổ tức', description: 'Biến động vốn chủ sở hữu trong kỳ.' },
  { id: 'f26', name: 'Dòng tiền thuần từ hoạt động kinh doanh', category: 'Ngân Sách & Dòng Tiền', equation: 'Dòng tiền thuần = Tiền thu vào - Tiền chi ra (trong HĐKD)', description: 'Khả năng tạo tiền từ cốt lõi kinh doanh.' },
  { id: 'f27', name: 'Hệ số tự tài trợ', category: 'Phân Tích Tài Chính', equation: 'Hệ số tự tài trợ = Vốn chủ sở hữu / Tổng nguồn vốn', description: 'Đánh giá tính độc lập về tài chính.' },
  { id: 'f28', name: 'Tỷ suất lợi nhuận gộp', category: 'Báo Cáo Kết Quả Kinh Doanh', equation: 'Tỷ suất LN gộp = (Lợi nhuận gộp / Doanh thu thuần) * 100%', description: 'Lợi nhuận thu được trên mỗi đồng doanh thu sau giá vốn.' },
  { id: 'f29', name: 'Giá trị sổ sách của cổ phiếu', category: 'Phân Tích Tài Chính', equation: 'BVPS = (Vốn CSH - Vốn ưu đãi) / Số lượng CP phổ thông', description: 'Giá trị tài sản ròng trên một cổ phiếu.' },
  { id: 'f30', name: 'Thu nhập mỗi cổ phiếu (EPS)', category: 'Phân Tích Tài Chính', equation: 'EPS = (Lợi nhuận sau thuế - Cổ tức ưu đãi) / Số lượng CP phổ thông', description: 'Phần lợi nhuận phân bổ cho mỗi cổ phiếu phổ thông.' },
  { id: 'f31', name: 'Hệ số P/E', category: 'Phân Tích Tài Chính', equation: 'P/E = Giá thị trường cổ phiếu / EPS', description: 'Thời gian hoàn vốn của các nhà đầu tư.' },
  { id: 'f32', name: 'Kế toán tổng hợp CPSX', category: 'Tính Giá Thành', equation: 'Tổng CPSX = Dở dang đầu kỳ + CP phát sinh - Dở dang cuối kỳ', description: 'Tính toán tổng chi phí sản xuất trong kỳ.' },
  { id: 'f33', name: 'Khấu hao theo số dư giảm dần', category: 'Thuế & Khấu Hao', equation: 'Mức khấu hao = Giá trị còn lại * Tỷ lệ khấu hao nhanh', description: 'Mức khấu hao giảm dần qua các năm.' },
  { id: 'f34', name: 'Khấu hao theo số lượng sản phẩm', category: 'Thuế & Khấu Hao', equation: 'Khấu hao = Sản lượng thực tế * Mức khấu hao đơn vị', description: 'Khấu hao dựa trên công suất sử dụng.' },
  { id: 'f35', name: 'Thuế GTGT phải nộp (Khấu trừ)', category: 'Thuế & Khấu Hao', equation: 'Thuế nộp = Thuế đầu ra - Thuế đầu vào được khấu trừ', description: 'Cách tính thuế GTGT phổ biến.' },
  { id: 'f36', name: 'Thuế Thu nhập doanh nghiệp (TNDN)', category: 'Thuế & Khấu Hao', equation: 'Thuế TNDN = (Thu nhập tính thuế - Quỹ KH&CN) * Thuế suất', description: 'Nghĩa vụ thuế trên lợi nhuận.' },
  { id: 'f37', name: 'Thu nhập tính thuế', category: 'Thuế & Khấu Hao', equation: 'TN tính thuế = Thu nhập chịu thuế - TN miễn thuế - Lỗ kết chuyển', description: 'Căn cứ để tính thuế TNDN.' },
  { id: 'f38', name: 'Doanh thu hòa vốn', category: 'Kế Toán Quản Trị', equation: 'Doanh thu hòa vốn = Tổng định phí / Tỷ lệ số dư đảm phí', description: 'Doanh số cần đạt để không lỗ.' },
  { id: 'f39', name: 'Định phí bình quân một sản phẩm', category: 'Tính Giá Thành', equation: 'Định phí đơn vị = Tổng định phí / Sản lượng thực tế', description: 'Thay đổi tỷ lệ nghịch với sản lượng.' },
  { id: 'f40', name: 'Biến phí đơn vị bình quân', category: 'Tính Giá Thành', equation: 'Biến phí đơn vị = Tổng biến phí / Sản lượng thực tế', description: 'Cố định trong phạm vi phù hợp.' },
  { id: 'f41', name: 'Hệ số nợ trên vốn chủ sở hữu (D/E)', category: 'Phân Tích Tài Chính', equation: 'D/E = Tổng nợ phải trả / Vốn chủ sở hữu', description: 'Tương quan giữa nợ và vốn tự có.' },
  { id: 'f42', name: 'Tỷ suất tự chủ tài chính', category: 'Phân Tích Tài Chính', equation: 'Tỷ suất tự chủ = Vốn chủ sở hữu / Tổng tài sản', description: 'Mức độ bền vững nguồn vốn.' },
  { id: 'f43', name: 'Hiệu suất sử dụng tổng tài sản', category: 'Phân Tích Tài Chính', equation: 'Vòng quay tổng TS = Doanh thu thuần / Tổng tài sản bình quân', description: 'Năng lực tạo doanh thu từ tài sản.' },
  { id: 'f44', name: 'Hiệu suất sử dụng tài sản cố định', category: 'Phân Tích Tài Chính', equation: 'Vòng quay TSCĐ = Doanh thu thuần / TSCĐ ròng bình quân', description: 'Hiệu quả đầu tư máy móc thiết bị.' },
  { id: 'f45', name: 'Thời gian luân chuyển hàng tồn kho', category: 'Phân Tích Tài Chính', equation: 'Thời gian quay kho = 360 / Vòng quay hàng tồn kho', description: 'Số ngày trung bình hàng nằm trong kho.' },
  { id: 'f46', name: 'Vòng quay các khoản phải trả', category: 'Phân Tích Tài Chính', equation: 'Vòng quay phải trả = Giá vốn hàng bán / Phải trả NCC bình quân', description: 'Tốc độ trả nợ cho nhà cung cấp.' },
  { id: 'f47', name: 'Chu kỳ kinh doanh', category: 'Phân Tích Tài Chính', equation: 'Chu kỳ kinh doanh = Kỳ thu tiền + Thời gian quay kho', description: 'Thời gian từ khi mua hàng đến khi thu tiền.' },
  { id: 'f48', name: 'Chu kỳ tiền mặt', category: 'Phân Tích Tài Chính', equation: 'Chu kỳ tiền = Chu kỳ kinh doanh - Kỳ thanh toán khoản phải trả', description: 'Thời gian doanh nghiệp bị đọng vốn.' },
  { id: 'f49', name: 'Hệ số khả năng trả nợ gốc và lãi', category: 'Phân Tích Tài Chính', equation: 'DSCR = EBITDA / (Gốc + Lãi nợ vay)', description: 'Khả năng đáp ứng nghĩa vụ nợ.' },
  { id: 'f50', name: 'Lợi nhuận trước thuế, lãi vay và khấu hao (EBITDA)', category: 'Báo Cáo Kết Quả Kinh Doanh', equation: 'EBITDA = EBIT + Khấu hao', description: 'Đo lường hiệu quả hoạt động tiền mặt.' },
  { id: 'f51', name: 'Lợi nhuận hoạt động (EBIT)', category: 'Báo Cáo Kết Quả Kinh Doanh', equation: 'EBIT = Lợi nhuận trước thuế + Lãi vay', description: 'Lợi nhuận từ hoạt động lõi.' },
  { id: 'f52', name: 'Tỷ lệ trả cổ tức', category: 'Phân Tích Tài Chính', equation: 'Tỷ lệ trả cổ tức = Cổ tức bằng tiền / Lợi nhuận sau thuế', description: 'Mức độ chia sẻ lợi nhuận với cổ đông.' },
  { id: 'f53', name: 'Mô hình Dupont (3 bước)', category: 'Phân Tích Tài Chính', equation: 'ROE = Biên LN ròng * Vòng quay tài sản * Đòn bẩy tài chính', description: 'Phân tích sâu các yếu tố tác động đến ROE.' },
  { id: 'f54', name: 'Thặng dư vốn cổ phần', category: 'Bảng Cân Đối Kế Toán', equation: 'Thặng dư = (Giá phát hành - Mệnh giá) * Số lượng CP', description: 'Chênh lệch mệnh giá khi phát hành cổ phiếu.' },
  { id: 'f55', name: 'Lợi nhuận giữ lại tích lũy', category: 'Bảng Cân Đối Kế Toán', equation: 'LN giữ lại cuối = LN giữ lại đầu + LN sau thuế - Cổ tức', description: 'Phần lợi nhuận tái đầu tư.' },
  { id: 'f56', name: 'Chi phí sử dụng vốn bình quân (WACC)', category: 'Phân Tích Tài Chính', equation: 'WACC = (E/V)*Re + (D/V)*Rd*(1-T)', description: 'Chi phí vốn trung bình của doanh nghiệp.' },
  { id: 'f57', name: 'Giá trị hiện tại (PV)', category: 'Ngân Sách & Dòng Tiền', equation: 'PV = FV / (1 + r)^n', description: 'Quy đổi tiền tương lai về hiện tại.' },
  { id: 'f58', name: 'Giá trị tương lai (FV)', category: 'Ngân Sách & Dòng Tiền', equation: 'FV = PV * (1 + r)^n', description: 'Giá trị của tiền sau một thời gian.' },
  { id: 'f59', name: 'Giá trị hiện tại thuần (NPV)', category: 'Ngân Sách & Dòng Tiền', equation: 'NPV = Tổng PV dòng tiền vào - Tổng PV dòng tiền ra', description: 'Tiêu chuẩn đánh giá dự án đầu tư.' },
  { id: 'f60', name: 'Chỉ số sinh lời (PI)', category: 'Ngân Sách & Dòng Tiền', equation: 'PI = Tổng PV dòng tiền vào / Vốn đầu tư ban đầu', description: 'Hiệu quả trên một đồng vốn đầu tư.' },
  { id: 'f61', name: 'Thời gian hoàn vốn (PP)', category: 'Ngân Sách & Dòng Tiền', equation: 'PP = Vốn đầu tư / Dòng tiền thuần hàng năm', description: 'Thời gian thu hồi vốn đầu tư ban đầu.' },
  { id: 'f62', name: 'Doanh thu mục tiêu', category: 'Kế Toán Quản Trị', equation: 'Doanh thu mục tiêu = (Định phí + Lợi nhuận mục tiêu) / Tỷ lệ SDĐP', description: 'Tính doanh số cần thiết để đạt mức lãi kỳ vọng.' },
  { id: 'f63', name: 'Lợi nhuận kinh tế (EVA)', category: 'Phân Tích Tài Chính', equation: 'EVA = NOPAT - (Vốn đầu tư * WACC)', description: 'Lợi nhuận thực sự sau khi trừ chi phí vốn.' },
  { id: 'f64', name: 'Vốn hóa thị trường', category: 'Phân Tích Tài Chính', equation: 'Vốn hóa = Giá thị trường cổ phiếu * Tổng số CP lưu hành', description: 'Giá trị của công ty trên sàn chứng khoán.' },
  { id: 'f65', name: 'Chỉ số thanh toán lãi vay', category: 'Phân Tích Tài Chính', equation: 'Tỉ số lãi vay = EBIT / Chi phí lãi vay', description: 'Khả năng trả lãi của doanh nghiệp.' },
  { id: 'f66', name: 'Tỷ lệ nợ trên vốn đầu tư', category: 'Phân Tích Tài Chính', equation: 'Nợ/Vốn = Tổng nợ / (Vốn CSH + Tổng nợ)', description: 'Đo lường cơ cấu vốn.' },
  { id: 'f67', name: 'Dòng tiền tự do (FCF)', category: 'Ngân Sách & Dòng Tiền', equation: 'FCF = Cash flow từ HĐKD - Chi tiêu vốn (CapEx)', description: 'Số tiền sẵn có để trả cho các nhà đầu tư.' },
  { id: 'f68', name: 'Lợi nhuận trên vốn đầu tư (ROI)', category: 'Phân Tích Tài Chính', equation: 'ROI = (Lợi nhuận / Vốn đầu tư) * 100%', description: 'Đánh giá tính hiệu quả của khoản đầu tư.' },
  { id: 'f69', name: 'Chi phí biến đổi (Biến phí)', category: 'Tính Giá Thành', equation: 'Biến phí = Biến phí đơn vị * Sản lượng', description: 'Chi phí thay đổi theo sản lượng.' },
  { id: 'f70', name: 'Giá bán dự kiến (Mark-up)', category: 'Tính Giá Thành', equation: 'Giá bán = Giá vốn + (Giá vốn * Tỷ lệ thặng số)', description: 'Xác định giá bán dựa trên chi phí.' },
  { id: 'f71', name: 'Hệ số quay vòng vốn chủ sở hữu', category: 'Phân Tích Tài Chính', equation: 'Vòng quay vốn CSH = Doanh thu thuần / Vốn CSH bình quân', description: 'Hiệu quả sử dụng vốn tự có.' },
  { id: 'f72', name: 'Hệ số tạo tiền', category: 'Ngân Sách & Dòng Tiền', equation: 'Hệ số tạo tiền = Dòng tiền từ HĐKD / Doanh thu thuần', description: 'Khả năng chuyển doanh thu thành tiền mặt.' },
  { id: 'f73', name: 'Tỷ trọng tài sản cố định', category: 'Phân Tích Tài Chính', equation: 'Tỷ trọng TSCĐ = (TSCĐ / Tổng tài sản) * 100%', description: 'Mức độ thâm dụng vốn vào tài sản cố định.' },
  { id: 'f74', name: 'Tỷ lệ nợ ngắn hạn trên nợ phải trả', category: 'Phân Tích Tài Chính', equation: 'Tỉ lệ nợ ngắn = Nợ ngắn hạn / Tổng nợ phải trả', description: 'Cấu trúc nợ của doanh nghiệp.' },
  { id: 'f75', name: 'Hệ số bảo đảm nợ bằng tài sản', category: 'Phân Tích Tài Chính', equation: 'Hệ số đảm bảo = Tổng tài sản / Tổng nợ phải trả', description: 'Khả năng bảo toàn nợ cho chủ nợ.' },
  { id: 'f76', name: 'Kỳ thanh toán nợ khách hàng bình quân', category: 'Phân Tích Tài Chính', equation: 'Kỳ phải trả = 360 / Vòng quay phải trả', description: 'Thời gian chiếm dụng vốn nhà cung cấp.' },
  { id: 'f77', name: 'Chi phí tài chính trên doanh thu', category: 'Phân Tích Tài Chính', equation: 'Tỉ lệ CP tài chính = (Chi phí tài chính / Doanh thu thuần) * 100%', description: 'Áp lực chi phí vay vốn trên doanh thu.' },
  { id: 'f78', name: 'Thu nhập ròng hoạt động (NOI)', category: 'Phân Tích Tài Chính', equation: 'NOI = Doanh thu hoạt động - Chi phí vận hành', description: 'Dòng tiền từ tài sản sinh lời (BĐS).' },
  { id: 'f79', name: 'Lợi suất cổ tức (Dividend Yield)', category: 'Phân Tích Tài Chính', equation: 'Lợi suất = Cổ tức một năm / Giá cổ phiếu hiện tại', description: 'Lợi nhuận tiền mặt từ đầu tư cổ phiếu.' },
  { id: 'f80', name: 'Giá vốn hàng bán (Chi tiết)', category: 'Báo Cáo Kết Quả Kinh Doanh', equation: 'GVHB = HTK đầu kỳ + Mua trong kỳ - HTK cuối kỳ', description: 'Công thức kiểm kê định kỳ phổ biến.' }
];

export const exercises: Exercise[] = [
  { id: 'e1', question: 'Công ty A có Nợ phải trả là 500 triệu và Vốn chủ sở hữu là 800 triệu. Tính Tổng tài sản?', category: 'Bảng Cân Đối Kế Toán', parameters: { 'Nợ': 500, 'Vốn CSH': 800 }, correctValue: 1300, unit: 'triệu VNĐ', explanation: 'Tài sản = Nợ + Vốn = 500 + 800 = 1300.' },
  { id: 'e2', question: 'Doanh thu thuần là 1,15 tỷ, giá vốn hàng bán là 700 triệu. Tính Lợi nhuận gộp?', category: 'Báo Cáo Kết Quả Kinh Doanh', parameters: { 'DT thuần': 1150, 'Giá vốn': 700 }, correctValue: 450, unit: 'triệu VNĐ', explanation: 'LN gộp = 1150 - 700 = 450.' },
  { id: 'e3', question: 'Tài sản ngắn hạn là 400 triệu, Nợ ngắn hạn là 200 triệu. Tính Tỉ số thanh toán hiện hành?', category: 'Phân Tích Tài Chính', parameters: { 'TSNH': 400, 'NNH': 200 }, correctValue: 2, unit: 'lần', explanation: 'TS hiện hành = 400 / 200 = 2.' },
  { id: 'e4', question: 'Nhập 100 sp giá 10k, nhập tiếp 200 sp giá 13k. Tính giá bình quân gia quyền một sản phẩm?', category: 'Quản Lý Hàng Tồn Kho', parameters: { 'SL1': 100, 'G1': 10, 'SL2': 200, 'G2': 13 }, correctValue: 12, unit: 'k VNĐ', explanation: '(100*10 + 200*13) / 300 = 3600 / 300 = 12.' },
  { id: 'e5', question: 'Nguyên giá máy 100 triệu, sử dụng 4 năm, không thanh lý. Tính khấu hao năm 1?', category: 'Thuế & Khấu Hao', parameters: { 'NG': 100, 'T': 4 }, correctValue: 25, unit: 'triệu VNĐ', explanation: '100 / 4 = 25.' },
  { id: 'e6', question: 'Doanh thu 1 tỷ, Lợi nhuận sau thuế 150 triệu. Tính ROS?', category: 'Phân Tích Tài Chính', parameters: { 'DT': 1000, 'LNST': 150 }, correctValue: 15, unit: '%', explanation: '150 / 1000 = 0.15 = 15%.' },
  { id: 'e7', question: 'Tài sản đầu kỳ 1,2 tỷ, cuối kỳ 1,4 tỷ. LNST 260 triệu. Tính ROA?', category: 'Phân Tích Tài Chính', parameters: { 'Dầu': 1200, 'Cuối': 1400, 'LN': 260 }, correctValue: 20, unit: '%', explanation: '260 / ((1200+1400)/2) = 260 / 1300 = 0.2 = 20%.' },
  { id: 'e8', question: 'Định phí 300 triệu, biến phí 60k/sp, giá bán 100k/sp. Tính sản lượng hòa vốn?', category: 'Tính Giá Thành', parameters: { 'FC': 300000, 'VC': 60, 'P': 100 }, correctValue: 7500, unit: 'sản phẩm', explanation: '300.000 / (100 - 60) = 7500.' },
  { id: 'e9', question: 'Tổng tài sản 2 tỷ, tổng nợ 1,2 tỷ. Tính hệ số nợ?', category: 'Phân Tích Tài Chính', parameters: { 'TS': 2000, 'Nợ': 1200 }, correctValue: 0.6, unit: '', explanation: '1200 / 2000 = 0.6.' },
  { id: 'e10', question: 'Tồn đầu 50 triệu, nhập 400 triệu, tồn cuối 30 triệu. Tính giá vốn hàng bán?', category: 'Báo Cáo Kết Quả Kinh Doanh', parameters: { 'Đầu': 50, 'Nhập': 400, 'Cuối': 30 }, correctValue: 420, unit: 'triệu VNĐ', explanation: '50 + 400 - 30 = 420.' },
  { id: 'e11', question: 'Vốn CSH đầu 1 tỷ, LNST 200 triệu, trả cổ tức 50 triệu. Tính vốn CSH cuối?', category: 'Bảng Cân Đối Kế Toán', parameters: { 'Đầu': 1000, 'LN': 200, 'Div': 50 }, correctValue: 1150, unit: 'triệu VNĐ', explanation: '1000 + 200 - 50 = 1150.' },
  { id: 'e12', question: 'Tài sản ngắn hạn 500 triệu, hàng tồn kho 150 triệu, nợ ngắn hạn 200 triệu. Tính tỉ số thanh toán nhanh?', category: 'Phân Tích Tài Chính', parameters: { 'TSNH': 500, 'HTK': 150, 'NNH': 200 }, correctValue: 1.75, unit: 'lần', explanation: '(500 - 150) / 200 = 1.75.' },
  { id: 'e13', question: 'Doanh thu thuần 2 tỷ, phải thu đầu kỳ 200, cuối kỳ 300. Tính vòng quay phải thu?', category: 'Phân Tích Tài Chính', parameters: { 'DT': 2000, 'P1': 200, 'P2': 300 }, correctValue: 8, unit: 'vòng', explanation: '2000 / ((200+300)/2) = 2000 / 250 = 8.' },
  { id: 'e14', question: 'Vòng quay phải thu là 10. Tính kỳ thu tiền bình quân?', category: 'Phân Tích Tài Chính', parameters: { 'VQ': 10 }, correctValue: 36, unit: 'ngày', explanation: '360 / 10 = 36.' },
  { id: 'e15', question: 'Giá vốn hàng bán 1,2 tỷ, HTK đầu kỳ 100, cuối kỳ 200. Tính vòng quay HTK?', category: 'Quản Lý Hàng Tồn Kho', parameters: { 'GV': 1200, 'T1': 100, 'T2': 200 }, correctValue: 8, unit: 'vòng', explanation: '1200 / 150 = 8.' },
  { id: 'e16', question: 'Giá bán 20k, biến phí 12k. Doanh thu 100 triệu. Tính tổng số dư đảm phí?', category: 'Kế Toán Quản Trị', parameters: { 'P': 20, 'V': 12, 'DT': 100000 }, correctValue: 40000, unit: 'k VNĐ', explanation: '100.000 * (20-12)/20 = 100.000 * 0.4 = 40.000.' },
  { id: 'e17', question: 'Lợi nhuận 100 triệu, thặng số đánh vào chi phí là 25%. Tính doanh thu mục tiêu?', category: 'Kế Toán Quản Trị', parameters: { 'LN': 100, 'M': 0.25 }, correctValue: 125, unit: 'triệu VNĐ', explanation: 'Nếu lãi là 25% thì Doanh thu = 100 + 0.25*100 = 125 (Giả định đơn giản).' },
  { id: 'e18', question: 'Cầm 100 triệu gửi ngân hàng lãi 10% năm. Tính giá trị sau 2 năm (lãi kép)?', category: 'Ngân Sách & Dòng Tiền', parameters: { 'PV': 100, 'r': 0.1, 'n': 2 }, correctValue: 121, unit: 'triệu VNĐ', explanation: '100 * (1.1)^2 = 121.' },
  { id: 'e19', question: 'Dự án đầu tư 500 triệu, năm 1 thu 300, năm 2 thu 400. Chi phí vốn 10%. Tính NPV?', category: 'Ngân Sách & Dòng Tiền', parameters: { 'V': 500, 'C1': 300, 'C2': 400, 'r': 0.1 }, correctValue: 103.3, unit: 'triệu VNĐ', explanation: '(300/1.1 + 400/1.21) - 500 = (272.7 + 330.6) - 500 = 103.3.' },
  { id: 'e20', question: 'Công ty có 1 triệu cổ phiếu phổ thông, LNST 2,5 tỷ. Tính EPS?', category: 'Phân Tích Tài Chính', parameters: { 'CP': 1, 'LN': 2500 }, correctValue: 2500, unit: 'VNĐ', explanation: '2500 triệu / 1 triệu cp = 2500 VNĐ.' },
  { id: 'e21', question: 'EPS là 2k, giá cổ phiếu 30k. Tính chỉ số P/E?', category: 'Phân Tích Tài Chính', parameters: { 'EPS': 2, 'P': 30 }, correctValue: 15, unit: 'lần', explanation: '30 / 2 = 15.' },
  { id: 'e22', question: 'Định phí 400 triệu, tỷ lệ SDĐP 40%. Tính doanh thu hòa vốn?', category: 'Kế Toán Quản Trị', parameters: { 'FC': 400, 'R': 0.4 }, correctValue: 1000, unit: 'triệu VNĐ', explanation: '400 / 0.4 = 1000.' },
  { id: 'e23', question: 'Tài sản ngắn hạn 600, nợ ngắn hạn 300. Tính vốn lưu động ròng?', category: 'Phân Tích Tài Chính', parameters: { 'TS': 600, 'Nợ': 300 }, correctValue: 300, unit: 'triệu VNĐ', explanation: '600 - 300 = 300.' },
  { id: 'e24', question: 'Vốn CSH 1,2 tỷ, tổng tài sản 2 tỷ. Tính hệ số tự tài trợ?', category: 'Phân Tích Tài Chính', parameters: { 'Vốn': 1200, 'TS': 2000 }, correctValue: 0.6, unit: '', explanation: '1200 / 2000 = 0.6.' },
  { id: 'e25', question: 'Doanh thu thuần 3 tỷ, vốn lưu động bình quân 500 triệu. Tính vòng quay vốn lưu động?', category: 'Phân Tích Tài Chính', parameters: { 'DT': 3000, 'V': 500 }, correctValue: 6, unit: 'vòng', explanation: '3000 / 500 = 6.' },
  { id: 'e26', question: 'Chi phí mua TSCĐ 500 triệu, thuế suất 20%. Tính lá chắn thuế khấu hao mỗi năm (sử dụng 5 năm)?', category: 'Thuế & Khấu Hao', parameters: { 'NG': 500, 'T': 0.2, 'n': 5 }, correctValue: 20, unit: 'triệu VNĐ', explanation: '(500 / 5) * 0.2 = 20.' },
  { id: 'e27', question: 'TSCĐ nguyên giá 200 triệu, khấu hao nhanh 40%/năm. Tính khấu hao năm 2?', category: 'Thuế & Khấu Hao', parameters: { 'NG': 200, 'r': 0.4 }, correctValue: 48, unit: 'triệu VNĐ', explanation: 'Năm 1: 200*0.4=80. Còn lại: 120. Năm 2: 120*0.4=48.' },
  { id: 'e28', question: 'Biên LN ròng 10%, Vòng quay tài sản 2.0, Đòn bẩy tài chính 1.5. Tính ROE theo Dupont?', category: 'Phân Tích Tài Chính', parameters: { 'M': 0.1, 'A': 2, 'L': 1.5 }, correctValue: 30, unit: '%', explanation: '0.1 * 2 * 1.5 = 0.3 = 30%.' },
  { id: 'e29', question: 'HTK cuối kỳ 300, giá vốn hàng bán kỳ 1,5 tỷ. Tính số ngày quay kho?', category: 'Quản Lý Hàng Tồn Kho', parameters: { 'Cuối': 300, 'GV': 1500 }, correctValue: 72, unit: 'ngày', explanation: '360 / (1500 / 300) = 360 / 5 = 72.' },
  { id: 'e30', question: 'Mua hàng 200 triệu, Thuế GTGT 10%. Tính tổng tiền thanh toán?', category: 'Thuế & Khấu Hao', parameters: { 'G': 200, 'T': 0.1 }, correctValue: 220, unit: 'triệu VNĐ', explanation: '200 + 20 = 220.' },
  // Adding more mock/repetitive exercises to reach exactly 82 if needed, but I will provide a unique set.
  { id: 'e31', question: 'Doanh thu thuần 5 tỷ, Giá vốn 3 tỷ. Tính Tỷ suất lợi nhuận gộp?', category: 'Báo Cáo Kết Quả Kinh Doanh', parameters: { 'DT': 5000, 'GV': 3000 }, correctValue: 40, unit: '%', explanation: '(5000-3000)/5000 = 0.4 = 40%.' },
  { id: 'e32', question: 'Nợ ngắn hạn 100, Nợ dài hạn 200, Tổng tài sản 600. Tính Hệ số nợ?', category: 'Phân Tích Tài Chính', parameters: { 'N1': 100, 'N2': 200, 'TS': 600 }, correctValue: 0.5, unit: '', explanation: '(100+200)/600 = 0.5.' },
  { id: 'e33', question: 'Sản lượng 1000 sp, Biến phí 50k, Định phí 20 triệu. Tính tổng chi phí sản xuất?', category: 'Tính Giá Thành', parameters: { 'SL': 1000, 'VC': 50, 'FC': 20000 }, correctValue: 70000, unit: 'k VNĐ', explanation: '1000*50 + 20000 = 70000.' },
  { id: 'e34', question: 'Tổng tài sản 1 tỷ, LN sau thuế 100 triệu. Tính ROA?', category: 'Phân Tích Tài Chính', parameters: { 'TS': 1000, 'LN': 100 }, correctValue: 10, unit: '%', explanation: '100 / 1000 = 0.1 = 10%.' },
  { id: 'e35', question: 'Vốn CSH 500 triệu, LN sau thuế 100 triệu. Tính ROE?', category: 'Phân Tích Tài Chính', parameters: { 'Vốn': 500, 'LN': 100 }, correctValue: 20, unit: '%', explanation: '100 / 500 = 0.2 = 20%.' },
  { id: 'e36', question: 'Doanh thu 2 tỷ, Vòng quay TS 2. Tính Tổng tài sản?', category: 'Phân Tích Tài Chính', parameters: { 'DT': 2000, 'VQ': 2 }, correctValue: 1000, unit: 'triệu VNĐ', explanation: '2000 / 2 = 1000.' },
  { id: 'e37', question: 'Thanh toán hiện hành 2.0, Nợ ngắn hạn 200. Tính Tài sản ngắn hạn?', category: 'Phân Tích Tài Chính', parameters: { 'H': 2, 'N': 200 }, correctValue: 400, unit: 'triệu VNĐ', explanation: '2 * 200 = 400.' },
  { id: 'e38', question: 'Dòng tiền vào 500, dòng tiền ra 300. Tính dòng tiền thuần?', category: 'Ngân Sách & Dòng Tiền', parameters: { 'In': 500, 'Out': 300 }, correctValue: 200, unit: 'triệu VNĐ', explanation: '500 - 300 = 200.' },
  { id: 'e39', question: 'Khoản thu khách hàng ban đầu 50, bán nợ thêm 150, đã thu 100. Tính khoản thu cuối?', category: 'Bảng Cân Đối Kế Toán', parameters: { 'D': 50, 'B': 150, 'T': 100 }, correctValue: 100, unit: 'triệu VNĐ', explanation: '50 + 150 - 100 = 100.' },
  { id: 'e40', question: 'CP nguyên vật liệu 300, CP nhân công 200, CP SX chung 100. Tính giá thành sp (trong kỳ không dở dang)?', category: 'Tính Giá Thành', parameters: { 'NVL': 300, 'NC': 200, 'SXC': 100 }, correctValue: 600, unit: 'triệu VNĐ', explanation: '300 + 200 + 100 = 600.' },
  { id: 'e41', question: 'DN nộp thuế GTGT trực tiếp trên doanh thu 5%. Doanh thu 100 triệu. Tính thuế?', category: 'Thuế & Khấu Hao', parameters: { 'DT': 100, 'R': 0.05 }, correctValue: 5, unit: 'triệu VNĐ', explanation: '100 * 0.05 = 5.' },
  { id: 'e42', question: 'Giá thành định mức 100, thực tế 105. Tính biến động giá thành?', category: 'Kế Toán Quản Trị', parameters: { 'S': 100, 'A': 105 }, correctValue: 5, unit: 'triệu VNĐ', explanation: '105 - 100 = 5.' },
  { id: 'e43', question: 'Vốn hóa thị trường 500 tỷ, vốn CSH 250 tỷ. Tính chỉ số P/B?', category: 'Phân Tích Tài Chính', parameters: { 'M': 500, 'B': 250 }, correctValue: 2, unit: 'lần', explanation: '500 / 250 = 2.' },
  { id: 'e44', question: 'Cổ tức 2k/cp, giá CP 40k. Tính Dividend Yield?', category: 'Phân Tích Tài Chính', parameters: { 'D': 2, 'P': 40 }, correctValue: 5, unit: '%', explanation: '2 / 40 = 0.05 = 5%.' },
  { id: 'e45', question: 'Tỷ lệ nợ 60%, Tổng tài sản 1 tỷ. Tính Vốn chủ sở hữu?', category: 'Phân Tích Tài Chính', parameters: { 'R': 0.6, 'TS': 1000 }, correctValue: 400, unit: 'triệu VNĐ', explanation: '1000 * (1 - 0.6) = 400.' },
  { id: 'e46', question: 'Doanh thu thuần 500, Biến phí 300, Định phí 100. Tính Lợi nhuận thuần?', category: 'Báo Cáo Kết Quả Kinh Doanh', parameters: { 'DT': 500, 'VC': 300, 'FC': 100 }, correctValue: 100, unit: 'triệu VNĐ', explanation: '500 - 300 - 100 = 100.' },
  { id: 'e47', question: 'Dòng tiền HĐKD 400, chi đầu tư 150. Tính FCF?', category: 'Ngân Sách & Dòng Tiền', parameters: { 'C': 400, 'I': 150 }, correctValue: 250, unit: 'triệu VNĐ', explanation: '400 - 150 = 250.' },
  { id: 'e48', question: 'Doanh thu hòa vốn 800, Doanh thu thực tế 1 tỷ. Tính biên độ an toàn theo doanh thu?', category: 'Kế Toán Quản Trị', parameters: { 'BEP': 800, 'Act': 1000 }, correctValue: 200, unit: 'triệu VNĐ', explanation: '1000 - 800 = 200.' },
  { id: 'e49', question: 'Giá nhập 10, Thuế nhập khẩu 30%. Tính giá vốn hàng nhập?', category: 'Quản Lý Hàng Tồn Kho', parameters: { 'P': 10, 'T': 0.3 }, correctValue: 13, unit: 'k VNĐ', explanation: '10 * (1 + 0.3) = 13.' },
  { id: 'e50', question: 'EBIT 300, Chi phí lãi vay 50. Tính Tỉ số lãi vay?', category: 'Phân Tích Tài Chính', parameters: { 'EB': 300, 'Int': 50 }, correctValue: 6, unit: 'lần', explanation: '300 / 50 = 6.' },
  { id: 'e51', question: 'LN trước thuế 250, thuế TNDN 20%. Tính LN sau thuế?', category: 'Báo Cáo Kết Quả Kinh Doanh', parameters: { 'EBT': 250, 'T': 0.2 }, correctValue: 200, unit: 'triệu VNĐ', explanation: '250 * (1-0.2) = 200.' },
  { id: 'e52', question: 'Tồn kho bình quân 100, GVHB 600. Tính vòng quay HTK?', category: 'Quản Lý Hàng Tồn Kho', parameters: { 'Avg': 100, 'COGS': 600 }, correctValue: 6, unit: 'vòng', explanation: '600 / 100 = 6.' },
  { id: 'e53', question: 'Giá trị dở dang đầu 20, chi phí phát sinh 100, dở dang cuối 10. Tính tổng giá thành?', category: 'Tính Giá Thành', parameters: { 'D1': 20, 'CP': 100, 'D2': 10 }, correctValue: 110, unit: 'triệu VNĐ', explanation: '20 + 100 - 10 = 110.' },
  { id: 'e54', question: 'Mệnh giá 10k, giá phát hành 15k, số lượng 100k. Tính thặng số vốn cổ phần?', category: 'Bảng Cân Đối Kế Toán', parameters: { 'P': 15, 'M': 10, 'Q': 100 }, correctValue: 500, unit: 'triệu VNĐ', explanation: '(15-10)*100 = 500.' },
  { id: 'e55', question: 'Tiền mặt 50, Phải thu 150, Hàng tồn 200. Tính Tài sản ngắn hạn?', category: 'Bảng Cân Đối Kế Toán', parameters: { 'C': 50, 'R': 150, 'I': 200 }, correctValue: 400, unit: 'triệu VNĐ', explanation: '50 + 150 + 200 = 400.' },
  { id: 'e56', question: 'TSCĐ nguyên giá 1,2 tỷ, khấu hao lũy kế 400 triệu. Tính giá trị còn lại (Net Book Value)?', category: 'Thuế & Khấu Hao', parameters: { 'G': 1200, 'A': 400 }, correctValue: 800, unit: 'triệu VNĐ', explanation: '1200 - 400 = 800.' },
  { id: 'e57', question: 'Doanh thu thuần 10 tỷ, Phải thu khách hàng 2 tỷ. Tính thời gian thu hồi vốn (Kỳ thu tiền)?', category: 'Phân Tích Tài Chính', parameters: { 'DT': 10000, 'P': 2000 }, correctValue: 72, unit: 'ngày', explanation: '360 / (10000 / 2000) = 72.' },
  { id: 'e58', question: 'Lãi vay 50, LNST 200, Thuế suất 20%. Tính EBIT?', category: 'Báo Cáo Kết Quả Kinh Doanh', parameters: { 'Int': 50, 'NI': 200, 'T': 0.2 }, correctValue: 300, unit: 'triệu VNĐ', explanation: '200 / 0.8 + 50 = 250 + 50 = 300.' },
  { id: 'e59', question: 'Dự án thu nhập 100/năm vĩnh viễn, lãi suất 10%. Tính Giá trị hiện tại (PV)?', category: 'Ngân Sách & Dòng Tiền', parameters: { 'C': 100, 'r': 0.1 }, correctValue: 1000, unit: 'triệu VNĐ', explanation: '100 / 0.1 = 1000.' },
  { id: 'e60', question: 'Công ty chia 20% cổ tức bằng tiền trên mệnh giá 10k. Bạn có 1000 cổ phiếu. Tính số tiền nhận được?', category: 'Phân Tích Tài Chính', parameters: { 'R': 0.2, 'M': 10, 'Q': 1000 }, correctValue: 2, unit: 'triệu VNĐ', explanation: '10.000 * 0.2 * 1000 = 2.000.000.' },
  { id: 'e61', question: 'Vốn đầu tư 1 tỷ, LN năm 200 triệu. Tính ROI?', category: 'Phân Tích Tài Chính', parameters: { 'V': 1000, 'L': 200 }, correctValue: 20, unit: '%', explanation: '200 / 1000 = 0.2 = 20%.' },
  { id: 'e62', question: 'Lợi nhuận gộp 500, Doanh thu 2 tỷ. Tính Tỷ suất LN gộp?', category: 'Báo Cáo Kết Quả Kinh Doanh', parameters: { 'G': 500, 'R': 2000 }, correctValue: 25, unit: '%', explanation: '500 / 2000 = 0.25 = 25%.' },
  { id: 'e63', question: 'Chỉ số thanh toán nhanh 1.0, Nợ ngắn hạn 300, Tài sản ngắn hạn 500. Tính giá trị Hàng tồn kho?', category: 'Phân Tích Tài Chính', parameters: { 'Q': 1, 'N': 300, 'C': 500 }, correctValue: 200, unit: 'triệu VNĐ', explanation: '500 - (1 * 300) = 200.' },
  { id: 'e64', question: 'Tỷ trọng TSCĐ là 60%, Tổng tài sản 5 tỷ. Tính giá trị TSCĐ?', category: 'Phân Tích Tài Chính', parameters: { 'R': 0.6, 'A': 5000 }, correctValue: 3000, unit: 'triệu VNĐ', explanation: '5000 * 0.6 = 3000.' },
  { id: 'e65', question: 'Khoản phải trả NCC đầu kỳ 100, cuối kỳ 200, mua hàng trong kỳ 1,2 tỷ. Tính vòng quay phải trả?', category: 'Phân Tích Tài Chính', parameters: { 'D': 100, 'C': 200, 'B': 1200 }, correctValue: 8, unit: 'vòng', explanation: '1200 / 150 = 8.' },
  { id: 'e66', question: 'Vốn vay 400 (lãi 10%), Vốn CSH 600 (lãi 15%). Coi như không thuế. Tính WACC?', category: 'Phân Tích Tài Chính', parameters: { 'D': 400, 'Rd': 0.1, 'E': 600, 'Re': 0.15 }, correctValue: 13, unit: '%', explanation: '(400/1000)*0.1 + (600/1000)*0.15 = 0.04 + 0.09 = 0.13 = 13%.' },
  { id: 'e67', question: 'Doanh thu thuần 1 tỷ, LN hoạt động 400. Tính Operating Margin?', category: 'Báo Cáo Kết Quả Kinh Doanh', parameters: { 'R': 1000, 'O': 400 }, correctValue: 40, unit: '%', explanation: '400 / 1000 = 0.4 = 40%.' },
  { id: 'e68', question: 'Kỳ thu tiền 40 ngày, Số ngày quay kho 60 ngày. Tính chu kỳ kinh doanh?', category: 'Phân Tích Tài Chính', parameters: { 'R': 40, 'I': 60 }, correctValue: 100, unit: 'ngày', explanation: '40 + 60 = 100.' },
  { id: 'e69', question: 'Chu kỳ kinh doanh 100 ngày, kỳ thanh toán 30 ngày. Tính chu kỳ tiền?', category: 'Phân Tích Tài Chính', parameters: { 'B': 100, 'P': 30 }, correctValue: 70, unit: 'ngày', explanation: '100 - 30 = 70.' },
  { id: 'e70', question: 'Tổng tài sản 10 tỷ, Nợ phải trả 7 tỷ. Tính Tỷ suất tự chủ tài chính?', category: 'Phân Tích Tài Chính', parameters: { 'A': 10000, 'L': 7000 }, correctValue: 30, unit: '%', explanation: '(10000-7000)/10000 = 3000/10000 = 0.3 = 30%.' },
  { id: 'e71', question: 'Chi phí lãi vay 20, Thuế TNDN 40. Tính Tổng chi phí tài chính và thuế?', category: 'Báo Cáo Kết Quả Kinh Doanh', parameters: { 'I': 20, 'T': 40 }, correctValue: 60, unit: 'triệu VNĐ', explanation: '20 + 40 = 60.' },
  { id: 'e72', question: 'Vốn CSH 1 tỷ. Hệ số quay vòng vốn CSH là 3. Tính doanh thu thuần?', category: 'Phân Tích Tài Chính', parameters: { 'V': 1000, 'VQ': 3 }, correctValue: 3000, unit: 'triệu VNĐ', explanation: '1000 * 3 = 3000.' },
  { id: 'e73', question: 'Doanh thu 2 tỷ, chi phí NVL chiếm 50%. Tính chi phí NVL?', category: 'Tính Giá Thành', parameters: { 'DT': 2000, 'R': 0.5 }, correctValue: 1000, unit: 'triệu VNĐ', explanation: '2000 * 0.5 = 1000.' },
  { id: 'e74', question: 'Nợ ngắn hạn chiếm 70% tổng nợ. Tổng nợ là 1 tỷ. Tính nợ dài hạn?', category: 'Phân Tích Tài Chính', parameters: { 'R': 0.7, 'L': 1000 }, correctValue: 300, unit: 'triệu VNĐ', explanation: '1000 * 0.3 = 300.' },
  { id: 'e75', question: 'TSCĐ 2 tỷ, Tổng tài sản 5 tỷ. Tính tỷ trọng tài sản ngắn hạn?', category: 'Phân Tích Tài Chính', parameters: { 'F': 2000, 'A': 5000 }, correctValue: 60, unit: '%', explanation: '(5000-2000)/5000 = 0.6 = 60%.' },
  { id: 'e76', question: 'LN ròng 100, EBITDA 150. Tính khấu hao (giả sử không lãi và thuế)?', category: 'Báo Cáo Kết Quả Kinh Doanh', parameters: { 'NI': 100, 'EB': 150 }, correctValue: 50, unit: 'triệu VNĐ', explanation: '150 - 100 = 50.' },
  { id: 'e77', question: 'Giá bán 100k, Mark-up trên giá vốn là 25%. Tính giá vốn (giả định đơn giản)?', category: 'Tính Giá Thành', parameters: { 'P': 100, 'M': 0.25 }, correctValue: 80, unit: 'k VNĐ', explanation: '100 / 1.25 = 80.' },
  { id: 'e78', question: 'Cơ cấu vốn: Nợ 40%, Vốn CSH 60%. Tính đòn bẩy tài chính (Assets/Equity)?', category: 'Phân Tích Tài Chính', parameters: { 'L': 0.4, 'E': 0.6 }, correctValue: 1.67, unit: 'lần', explanation: '1 / 0.6 ≈ 1.67.' },
  { id: 'e79', question: 'Hệ số đảm bảo nợ 1,2 lần. Tổng nợ 1 tỷ. Tính Tổng tài sản?', category: 'Phân Tích Tài Chính', parameters: { 'R': 1.2, 'L': 1000 }, correctValue: 1200, unit: 'triệu VNĐ', explanation: '1.2 * 1000 = 1200.' },
  { id: 'e80', question: 'Giá trị hiện tại của dự án là 1 tỷ, chi phí đầu tư 800 triệu. Tính PI?', category: 'Ngân Sách & Dòng Tiền', parameters: { 'PV': 1000, 'I': 800 }, correctValue: 1.25, unit: '', explanation: '1000 / 800 = 1.25.' },
  { id: 'e81', question: 'Vốn lưu động ròng âm 200 triệu. Nợ ngắn hạn 500 triệu. Tính Tài sản ngắn hạn?', category: 'Phân Tích Tài Chính', parameters: { 'WC': -200, 'L': 500 }, correctValue: 300, unit: 'triệu VNĐ', explanation: '500 - 200 = 300.' },
  { id: 'e82', question: 'DN có EBIT 200, WACC 10%, Vốn đầu tư 1,5 tỷ. Giả sử không thuế. Tính EVA?', category: 'Phân Tích Tài Chính', parameters: { 'EB': 200, 'W': 0.1, 'C': 1500 }, correctValue: 50, unit: 'triệu VNĐ', explanation: '200 - (1500 * 0.1) = 200 - 150 = 50.' }
];
